# 表达式和控制结构

## 控制结构

和C一样，存在if、else、while、do、for、break、continue、return，并且对于外部函数调用和合约创建调用支持try/catch

没有什么类型可以转换成boolean类型，if(1){...}是无效的

## 函数调用

### 内部函数调用

合约内的函数可以被直接调用，内部函数调用会被EVM解释为简单的内存跳转，而不会清除内存

### 外部函数调用

可以使用this.f()，c.f()方式进行外部函数调用，其中c指合约，f指合约c的函数，外部函数调用不会直接通过内存跳转，在构造函数中不能使用this因为合约还未创建

要调用其它合约必须使用外部调用，对于一个外部调用，所有函数参数都得拷贝到内存中

当调用其它合于函数时，可以通过{value: 10, gas: 10000}指定gas上限和发送的以太币

### 名称调用和匿名函数参数

通过参数名称指定参数来可以使用任意顺序

```js
function f() public{
    set({value:2, key:3});
}

function set(uint key, uint value) public{
    ...
}
```

### 忽略函数参数名称

为命名的函数参数将会被忽略，这些参数会被放在栈上但不可访问

```js
contract C{
    function(uint k, uint) public pure returns(uint){
        return k;
    }
}
```

## 通过new创建合约

可以使用new来创建其它合约，但创建合约时必须要有代码，在创建合约时可以使用value发送ether到目的合约，但不能限制gas

```js
constract D{
    uint public x;
    constructor(uint a) payable{
        x = a;
    }
}

constract C{
    D d = new D(4);
    
    function createD(uint arg) public{
        D newD = new D(arg);
        newD.x();
    }
    
    function createAndEndowD(uint arg, uint amount) public payable{
        D newD = new D{value: amount}(arg);
        newD.x();
    }
}
```

### 通过盐值来创建合约

当创建合约时，合约地址由创建合约的地址以及该地址已经创建的合约数计算而来

如果制定了盐值，合约地址则由创建合约的地址、合约的代码、合约构造函数计算而来

```js
contract D{
    uint public x;
    constructor(uint a){
        x = a;
    }
}

constract C{
    function createDSalted(bytes32 salt, uint arg) public{
        address predictedAddress = address(uint160(uint(keccak256(abi.encodePacked(
        	bytes1(0xff),
            address(this),
            salt,
            keccak256(abi.encodePacked(type(D).creationCode, arg))
        )))));
        D d = new D{salt:salt}(arg);
        require(address(d) == predictedAddress);
    }
}
```

## 赋值

### 返回多值

solidity支持元组，函数返回的元素可以被赋值给新创建的变量也可以赋值给已存在的变量

```
contract C{
	uint index;
	function f() public pure returns(uint, bool, uint){
		return (7, true, 2);
	}
	function g() public{
		(uint x, , uint y) = f();
		(x, y) = (y, x);
		(index, , ) = f();
		uint a;
		(a, ,uint b) = f();//错误,无法将已声明的变量和未声明的变量混合
	}
}
```

### 变量作用域

声明的变量会有一个默认初始值，bool为false，uint、int为0，bytes1到bytes32为0，bytes和string为空字节或者空串，enum为第一个成员的值

变量的作用域为从声明到大括号结束，但在函数、合约外声明的变量对于其它函数、合约是可见的，即使这些变量的声明在某些函数、合约之后

## 检查和不检查算术

所有算数操作默认在上溢或者下溢后还原，可以使用unchecked来不检查是否溢出

```js
function f(uint a, uint b) pure public returns(uint){
    unchecked{return a - b;}
}
```

尽管使用了unchecked，仍然可以检测除以0的操作

移为运算符不会执行溢出检查，会导致截断的显示的类型转换不会有溢出检查

## 错误处理

solidity使用state-reverting异常来处理错误，该异常会撤销当前调用所发生的所有变化，如果在一个子调用中发生了异常，该异常自动向上抛出，直到被try/catch捕获

### assert和require

assert和require都可用于当条件不满足时抛出异常

assert函数会创建Panic(uint256)错误，assert函数只应该用于测试内部错误，一个Panic异常由以下场景产生：

* 0x00：用于编译器插入panic
* 0x01：assert参数为false
* 0x11：算术操作导致溢出
* 0x12：除0或模0
* 0x21：将一个负数或者很大的一个属转为枚举类型
* 0x22：访问一个没有被正确编码的storage字节数组
* 0x31：对一个空数组调用pop()
* 0x32：访问数组的索引越界
* 0x41：分配太多内存或者创建的数组太大
* 0x51：调用一个未赋值的函数变量

require函数会创建一个不带任何数据的错误或者一个Error(string)类型的错误，require函数应该被用于确保在执行期间不能被检测到的无效条件，一个Error(string)异常由以下场景产生：

* 调用require(x)，x为false
* 使用revert()或者revert("description")
* 调用没有代码的合约的外部函数
* 通过没有声明payable外部函数接收到ether

以下场景既不会产生Error也不会产生Panic：

* transfer函数失败
* 通过消息调用来调用一个函数，但该函数并没有正确结束，除了以下几个底层操作不会产生异常：call、send、delegatecall、callcode、staticcall，这几个函数不会抛出异常但是会返回false
* 使用new创建合约，但是合约创建操作并没有完成

### revert

revert有两种用法：

* revert()，revert("abc")，前一种不会有任何错误信息，后一种会创建Error(string)错误
* revert CustomError(arg1, arg2)

### try/catch

```js
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.8.1;

interface DataFeed { function getData(address token) external returns (uint value); }

contract FeedConsumer {
    DataFeed feed;
    uint errorCount;
    function rate(address token) public returns (uint value, bool success) {
        // Permanently disable the mechanism if there are
        // more than 10 errors.
        require(errorCount < 10);
        try feed.getData(token) returns (uint v) {
            return (v, true);
        } catch Error(string memory /*reason*/) {
            // This is executed in case
            // revert was called inside getData
            // and a reason string was provided.
            errorCount++;
            return (0, false);
        } catch Panic(uint /*errorCode*/) {
            // This is executed in case of a panic,
            // i.e. a serious error like division by zero
            // or overflow. The error code can be used
            // to determine the kind of error.
            errorCount++;
            return (0, false);
        } catch (bytes memory /*lowLevelData*/) {
            // This is executed in case revert() was used.
            errorCount++;
            return (0, false);
        }
    }
}
```

在try后需要跟上一个外部函数调用或者合约创建，solidity支持不同的catch来捕获不同类型错误：

* catch Error(string memory reason)，捕获由revert("a")或者require(false, "a")产生的错误
* catch Panic(uint errorCode){...}，捕获panic错误
* catch (bytes memory lowLevelData){...}，错误签名不和其它语句匹配时会执行该语句
* catch{...}，如果对错误不感兴趣可以不写错误类型

## 参考

[Expressions and Control Structures](https://docs.soliditylang.org/en/develop/control-structures.html#)

